# Generated by Django 5.1.1 on 2024-10-22 10:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='response',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
