# Generated by Django 5.1.3 on 2025-01-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccess',
        ),
    ]
