# Generated by Django 5.1.1 on 2024-11-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0003_prompthistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
