# Generated by Django 5.1.3 on 2025-01-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0004_prompthistory_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_numbers', models.TextField()),
                ('document_name', models.TextField()),
            ],
            options={
                'db_table': 'user_access',
                'managed': False,
            },
        ),
    ]
