# Generated by Django 5.1.3 on 2025-01-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0005_useraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUsingCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_using_collection', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
