# Generated by Django 5.1.3 on 2025-01-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0006_currentusingcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='thumbs_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
